name: Publish to VS Marketplace

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GH_TOKEN}}
          workflow: release_build_and_deploy.yml
          workflow_conclusion: success

      - name: Publish Release to Marketplace
        uses: CalvinAllen/action-vs-marketplace-publish@v1
        with:
          marketplace-pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          publish-manifest-path: ./extension.manifest.json
          vsix-path: ./artifact/MyCopyExtensionVs.vsix
