name: Publish to VS Marketplace

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: release_build_and_deploy.yml
          workflow_conclusion: success

      - name: Publish Release to Marketplace
        uses: cezarypiatek/VsixPublisherAction@1.1
        with:
          personal-access-code: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          publish-manifest-file: ./extension.manifest.json
          extension-file: ./artifact/MyCopyExtensionVs.vsix
