name: 'Build'
  
on:
  workflow_dispatch:
  
jobs:
  Release-Build-and-Deploy: 
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: microsoft/setup-msbuild@v2
    
    - name: 2. Bootstrapping NuGet Installer
      uses: nuget/setup-nuget@v2
    
    - name: 3. Restoring Packages
      run: nuget restore ./MyCopyExtensionVs.sln
    
    - name: 4. Building Project
      run: msbuild './MyCopyExtensionVs.csproj' /p:configuration='Release' /p:platform='x64'

    - name: 5. Publishing Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: './bin/x64/Release/MyCopyExtensionVs.vsix'
